# ETL Streamers progress subscribersde Twitch de https://twitchtracker.com/channels/ranking

In [1]:
# Instalacion de librerias
#!pip install BeautifulSoup
!pip install -U selenium
!pip3 install -U webdriver-manager
!pip install pandas

Requirement already satisfied: selenium in c:\users\xoel\anaconda3\lib\site-packages (4.4.3)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\xoel\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\xoel\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio~=0.17 in c:\users\xoel\anaconda3\lib\site-packages (from selenium) (0.21.0)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\xoel\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: attrs>=19.2.0 in c:\users\xoel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\xoel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: cffi>=1.14 in c:\users\xoel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: idna in c:\users\xoel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sortedcontainers in c:\users\xoel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: sniffio in c:\users\xoel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: outcome in c:\users\xoel\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: pycparser in c:\users\xoel\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\xoel\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\xoel\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\xoel\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.13.0)
Requirement already satisfied: webdriver-manager in c:\users\xoel\anaconda3\lib\site-packages (3.8.3)
Requirement already satisfied: tqdm in c:\users\xoel\anaconda3\lib\site-packages (from webdriver-manager) (4.64.0)
Requirement already satisfied: python-dotenv in c:\users\xoel\anaconda3\lib\site-packages (from webdriver-manager) (0.21.0)
Requirement already satisfied: requests in c:\users\xoel\anaconda3\lib\site-packages (from webdriver-manager) (2.27.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\xoel\anaconda3\lib\site-packages (from requests->webdriver-manager) (1.26.9)
Requirement already satisfied: idna<4,>=2.5 in c:\users\xoel\anaconda3\lib\site-packages (from requests->webdriver-manager) (3.3)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\xoel\anaconda3\lib\site-packages (from requests->webdriver-manager) (2.0.4)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\xoel\anaconda3\lib\site-packages (from requests->webdriver-manager) (2021.10.8)
Requirement already satisfied: colorama in c:\users\xoel\anaconda3\lib\site-packages (from tqdm->webdriver-manager) (0.4.4)
Requirement already satisfied: pandas in c:\users\xoel\anaconda3\lib\site-packages (1.4.2)
Requirement already satisfied: pytz>=2020.1 in c:\users\xoel\anaconda3\lib\site-packages (from pandas) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in c:\users\xoel\anaconda3\lib\site-packages (from pandas) (2.8.2)
Requirement already satisfied: numpy>=1.18.5 in c:\users\xoel\anaconda3\lib\site-packages (from pandas) (1.21.5)
Requirement already satisfied: six>=1.5 in c:\users\xoel\anaconda3\lib\site-packages (from python-dateutil>=2.8.1->pandas) (1.16.0)

In [2]:
# LIBRERIAS

# Generales
import time
import requests
import urllib.request
import csv
from datetime import datetime

# Gestion de datos
import pandas as pd

# Automatizacion
#from bs4 import BeautifulSoup
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.chrome.service import Service
import selenium
#from webdriver_manager.chrome import ChromeDriverManage

In [3]:
driver = webdriver.Chrome()

In [4]:
opts = webdriver.ChromeOptions()
#opts.add_argument('--headless')
driver = webdriver.Chrome(options=opts)

In [5]:
# Generador del veiculo driver addcion de atributos y parametros
#opts = Options()

# Seleccionar el driver
#driver = webdriver.Chrome('./chromedriver.exe', options=opts)

# Maximizador de ventada del navegador web

#driver.maximize_window()

In [6]:
driver.set_window_position(0, 0)
driver.set_window_size(1920, 1080)

In [7]:
# Ir a pagina de Twitchtracker.com subsc
url = 'https://twitchtracker.com/'
driver.get(url)

In [8]:
#
#
#
#
#    Extraer la lista de los 1000 mejores Streamers 
#
#
#
#

## E-xtract

In [26]:
# Extraccion de datos del TOP1000 de Twitchtracker

data_results=[]

def extrac_top1000():

    ###############################################################################
    
    #n_streamers = ['auronplay', 'xqc']

    #url_pagina = 'https://twitchtracker.com/xqc/subscribers'

    
    #driver.get(url_pagina)
    #time.sleep(2)
    
    
    
    ###############################################################################
    
    ###### Remove Adds whit go to down of page #########
    driver.execute_script("window.scrollTo(0,document.body.scrollHeight)")
        
    #El numero de range(XX) marca el numerador final de la pagina 50 serian el Top1000
      
    # Percorrer el sistema de paginacion
    
    n_paginas = driver.find_elements(By.XPATH, '//*[@id="subscribers_paginate"]/ul/li/a')
      
    initial_pag = 1
        
    now_page = initial_pag
     
    
    for pag in range(len(n_paginas)):             
        
        xpath_boton_paginacion = f'//*[@id="subscribers_paginate"]/ul/li[{now_page}]/a'
        
        boton_paginacion = driver.find_element(By.XPATH, xpath_boton_paginacion)
                      
        
        
        now_page = now_page + 1
        boton_paginacion.click()
        
        
        
        for i in range(1):

            #driver.get(url_pagina)

            # Nombre del Streamer
            nombres_streamer = driver.find_element(By.XPATH, '//*[@id="app-title"]')

            ## Table estractor
            # Nombre del Streamer
            month_year = driver.find_elements(By.XPATH, '//*[@id="subscribers"]/tbody/tr/td[1]')
            # Current Active Subs
            total_subs = driver.find_elements(By.XPATH, '//*[@id="subscribers"]/tbody/tr/td[2]')
            # Sub type Paid
            subs_type_prime = driver.find_elements(By.XPATH, '//*[@id="subscribers"]/tbody/tr/td[3]')
            # Sub type Tier1
            subs_type_tier_one = driver.find_elements(By.XPATH, '//*[@id="subscribers"]/tbody/tr/td[4]')
            # Sub type Tier2
            subs_type_tier_two = driver.find_elements(By.XPATH, '//*[@id="subscribers"]/tbody/tr/td[5]')
            # Sub type Tier3
            subs_type_tier_three = driver.find_elements(By.XPATH, '//*[@id="subscribers"]/tbody/tr/td[6]')
            # Sub type Unlisted
            subs_type_unlisted = driver.find_elements(By.XPATH, '//*[@id="subscribers"]/tbody/tr/td[7]')
            # Sub type Gifted
            subs_type_gifted = driver.find_elements(By.XPATH, '//*[@id="subscribers"]/tbody/tr/td[8]')
            
            for item in range(len(month_year)):
                temporal_data={
                                'Nombre Streamer': nombres_streamer.text,
                                'Month Year': month_year[item].text,
                                'Total Subs': total_subs[item].text,
                                'Subs Type Prime': subs_type_prime[item].text,
                                'Subs Type Tier 1($4.99)': subs_type_tier_one[item].text,
                                'Subs Type Tier 2($9.99)': subs_type_tier_two[item].text,
                                'Subs Type Tier 3($24.99)': subs_type_tier_three[item].text,
                                'Subs Type Unlisted': subs_type_unlisted[item].text,
                                'Subs Type Gifted': subs_type_gifted[item].text,
                                #'Raw data': raw_data[item].text,
                                }
                data_results.append(temporal_data)
             
        
        
        
            #n_paginas.click()
    
#extrac_top1000()

In [27]:
############################################################################

n_streamers = ['auronplay', 'xqc', 'elspreen', 'kaicenat', 'tarik']

for i in range(len(n_streamers)):
    
    # Permutacion de variable percorriendo la lista
    #######################################################
    
    url_pagina = f'https://twitchtracker.com/{n_streamers[i]}/subscribers'
    
    # Obtener la pagina mediante el navegador
    #######################################################
    driver.get(url_pagina)
    time.sleep(2)
    #######################################################
    
    #Ejecutar funcion extractiva
    #######################################################
    extrac_top1000()


    #######################################################







############################################################################
    
#numerador_pagina = 1
#url = 'https://twitchtracker.com/channels/ranking?page=' + str(numerador_pagina)

#url_pagina = f'https://twitchtracker.com/{nombre_streamer}/subscribers'



#url_pagina = 'https://twitchtracker.com/{n_streamers}/subscribers'

#url_pagina = 'https://twitchtracker.com/auronplay/subscribers'
#url_pagina = 'https://twitchtracker.com/xqc/subscribers'



###### Remove Adds #########

#boton_ads = driver.find_element(By.XPATH, '/html/body/ins[2]')    
#boton_ads.click()

In [28]:
# Mostramos datos del TOP50 de Twitchtracker
df_data = pd.DataFrame(data_results)
# Pasar datos por pantalla
df_data.head(40)

,Nombre Streamer,Month Year,Total Subs,Subs Type Prime,Subs Type Tier 1($4.99),Subs Type Tier 2($9.99),Subs Type Tier 3($24.99),Subs Type Unlisted,Subs Type Gifted
0,AURONPLAY,September 2022,"20,542","8,632","8,925",25,11,"2,949","1,862"
1,AURONPLAY,August 2022,"50,796","21,472","21,601",58,25,"7,640","3,761"
2,AURONPLAY,July 2022,"17,099","7,415","7,073",21,12,"2,578","1,475"
3,AURONPLAY,June 2022,"39,439","16,536","17,176",44,22,"5,661","4,032"
4,AURONPLAY,May 2022,"31,377","13,536","12,829",41,19,"4,952","1,927"
5,AURONPLAY,April 2022,"38,241","17,232","14,952",53,27,"5,977","2,943"
6,AURONPLAY,March 2022,"33,396","14,872","13,482",48,25,"4,969","2,767"
7,AURONPLAY,February 2022,"28,982","12,565","11,976",42,19,"4,380","2,568"
8,AURONPLAY,January 2022,"41,660","17,698","17,793",61,41,"6,067","4,133"
9,AURONPLAY,December 2021,"23,457","9,478","10,498",46,46,"3,389","2,141"
10,AURONPLAY,November 2021,"37,331","13,726","18,616",58,45,"4,886","7,457"
11,AURONPLAY,October 2021,"37,567","16,159","17,213",84,50,"4,061","5,125"
12,AURONPLAY,September 2021,"39,472","15,705","19,864",85,47,"3,771","8,255"
13,AURONPLAY,August 2021,"40,751","18,680","17,529",64,41,"4,437","6,939"
14,AURONPLAY,July 2021,"20,598","9,751","8,730",48,37,"2,032","3,209"
15,AURONPLAY,June 2021,"27,660","12,120","12,620",52,41,"2,827","5,910"
16,AURONPLAY,May 2021,"29,254","13,061","13,441",150,44,"2,558","8,087"
17,AURONPLAY,April 2021,"30,395","15,180","12,321",53,24,"2,817","7,465"
18,AURONPLAY,March 2021,"29,261","13,589","13,018",77,39,"2,538","8,223"
19,AURONPLAY,February 2021,"23,233","12,381","8,363",54,29,"2,406","3,860"
20,AURONPLAY,January 2021,"32,033","18,000","10,696",55,33,"3,249","5,137"
21,AURONPLAY,December 2020,"22,076","12,695","6,936",58,23,"2,364","2,665"
22,AURONPLAY,November 2020,"23,625","12,974","8,004",215,20,"2,412","4,317"
23,AURONPLAY,October 2020,"20,940","12,088","6,531",36,15,"2,270","1,955"
24,AURONPLAY,September 2020,"17,768","11,538","4,324",28,10,"1,868","1,416"
25,AURONPLAY,August 2020,"16,296","10,603","3,904",27,8,"1,754","1,398"
26,AURONPLAY,July 2020,"13,844","9,625","2,654",15,4,"1,546",760
27,AURONPLAY,June 2020,"14,934","10,743","3,421",14,4,752,"1,328"
28,AURONPLAY,May 2020,"18,928","14,176","3,716",19,15,"1,002","1,360"
29,AURONPLAY,April 2020,"15,239","11,352","3,005",14,12,856,"1,250"
30,AURONPLAY,March 2020,"10,022","7,255","2,269",20,6,472,"1,132"
31,AURONPLAY,February 2020,"9,961","7,169","2,340",16,6,430,"1,370"
32,AURONPLAY,January 2020,"10,285","8,248","1,485",16,12,524,496
33,AURONPLAY,December 2019,"7,749","6,479",882,10,0,378,286
34,AURONPLAY,November 2019,"4,358","3,212",975,4,0,167,312
35,XQC,September 2022,"34,124","14,706","10,302",47,47,"9,022","1,390"
36,XQC,August 2022,"77,180","31,232","19,156",91,161,"26,540","2,624"
37,XQC,July 2022,"82,051","34,694","23,544",112,87,"23,614","4,611"
38,XQC,June 2022,"84,713","34,231","23,081",122,88,"27,191","4,656"
39,XQC,May 2022,"94,120","38,263","25,592",130,103,"30,032","5,742"

## T-ransform

In [31]:
# Eliminar filas duplicadas
df_data = df_data.drop_duplicates(keep='last')

In [32]:
# Eliminar el \nhours
df_data = df_data.replace(to_replace='\nhours', value='', regex=True)

In [33]:
#Eliminar ,
df_data['Total Subs'] = df_data['Total Subs'].replace(to_replace=',', value='', regex=True)
df_data['Subs Type Prime'] = df_data['Subs Type Prime'].replace(to_replace=',', value='', regex=True)
df_data['Subs Type Tier 1($4.99)'] = df_data['Subs Type Tier 1($4.99)'].replace(to_replace=',', value='', regex=True)
df_data['Subs Type Tier 2($9.99)'] = df_data['Subs Type Tier 2($9.99)'].replace(to_replace=',', value='', regex=True)
df_data['Subs Type Tier 3($24.99)'] = df_data['Subs Type Tier 3($24.99)'].replace(to_replace=',', value='', regex=True)
df_data['Subs Type Unlisted'] = df_data['Subs Type Unlisted'].replace(to_replace=',', value='', regex=True)
df_data['Subs Type Gifted'] = df_data['Subs Type Gifted'].replace(to_replace=',', value='', regex=True)

In [34]:
# Eliminar .
df_data['Total Subs'] = df_data['Total Subs'].replace(to_replace='\.', value='', regex=True)
df_data['Subs Type Prime'] = df_data['Subs Type Prime'].replace(to_replace='\.', value='', regex=True)
df_data['Subs Type Tier 1($4.99)'] = df_data['Subs Type Tier 1($4.99)'].replace(to_replace='\.', value='', regex=True)
df_data['Subs Type Tier 2($9.99)'] = df_data['Subs Type Tier 2($9.99)'].replace(to_replace='\.', value='', regex=True)
df_data['Subs Type Tier 3($24.99)'] = df_data['Subs Type Tier 3($24.99)'].replace(to_replace='\.', value='', regex=True)
df_data['Subs Type Unlisted'] = df_data['Subs Type Unlisted'].replace(to_replace='\.', value='', regex=True)
df_data['Subs Type Gifted'] = df_data['Subs Type Gifted'].replace(to_replace='\.', value='', regex=True)

In [35]:
# Data clean
df_data

,Nombre Streamer,Month Year,Total Subs,Subs Type Prime,Subs Type Tier 1($4.99),Subs Type Tier 2($9.99),Subs Type Tier 3($24.99),Subs Type Unlisted,Subs Type Gifted
0,AURONPLAY,September 2022,20542,8632,8925,25,11,2949,1862
1,AURONPLAY,August 2022,50796,21472,21601,58,25,7640,3761
2,AURONPLAY,July 2022,17099,7415,7073,21,12,2578,1475
3,AURONPLAY,June 2022,39439,16536,17176,44,22,5661,4032
4,AURONPLAY,May 2022,31377,13536,12829,41,19,4952,1927
...,...,...,...,...,...,...,...,...,...
134,TARIK,March 2022,19336,9603,7087,16,27,2603,3759
135,TARIK,February 2022,12756,5787,5428,15,24,1502,3385
136,TARIK,January 2022,12456,4119,7056,17,17,1247,5182
137,TARIK,December 2021,11692,4552,5814,60,14,1252,4098
138,TARIK,November 2021,6094,1655,3962,8,7,462,3160

## L-oad

In [36]:
#Exportacion a CSV
now = datetime.now()
datos_top1000_progress_subcribers_streamers = 'datos_top1000_progress_subcribers_streamers' + str(now.year) + str(now.month) + str(now.day) + str(now.hour) + str(now.minute) + str(now.second)
df_data.to_csv(f'./{datos_top1000_progress_subcribers_streamers}.csv', index=False ,encoding='utf-8')